#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_

#define KINETIS_ADC_MUXSEL_A    0
#define KINETIS_ADC_MUXSEL_B    1

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_