#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_

#define KINETIS_ADC_MUXSEL_A    0
#define KINETIS_ADC_MUXSEL_B    1

#define KINETIS_ADC_TRG_PIT_0       0x4
#define KINETIS_ADC_TRG_PIT_1       0x5
#define KINETIS_ADC_TRG_PIT_2       0x6
#define KINETIS_ADC_TRG_PIT_3       0x7
#define KINETIS_ADC_TRG_FTM_0       0x8
#define KINETIS_ADC_TRG_FTM_1       0x9
#define KINETIS_ADC_TRG_FTM_2       0xa
#define KINETIS_ADC_TRG_FTM_3       0xb
#define KINETIS_ADC_TRG_RTC_ALRM    0xc
#define KINETIS_ADC_TRG_RTC_SEC     0xd
#define KINETIS_ADC_TRG_LPTMR       0xe

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_