#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_

#define KINETIS_ADC16_CHANNEL_TYPE_SE 0
#define KINETIS_ADC16_CHANNEL_TYPE_DF 1

#define KINETIS_ADC16_CHANNEL_MUX_A 0
#define KINETIS_ADC16_CHANNEL_MUX_B 1

#define KINETIS_ADC16_TRIGGER_PIT_0    0x4
#define KINETIS_ADC16_TRIGGER_PIT_1    0x5
#define KINETIS_ADC16_TRIGGER_PIT_2    0x6
#define KINETIS_ADC16_TRIGGER_PIT_3    0x7
#define KINETIS_ADC16_TRIGGER_FTM_0    0x8
#define KINETIS_ADC16_TRIGGER_FTM_1    0x9
#define KINETIS_ADC16_TRIGGER_FTM_2    0xa
#define KINETIS_ADC16_TRIGGER_FTM_3    0xb
#define KINETIS_ADC16_TRIGGER_RTC_ALRM 0xc
#define KINETIS_ADC16_TRIGGER_RTC_SEC  0xd
#define KINETIS_ADC16_TRIGGER_LPTMR    0xe

#define KINETIS_ADC16_CLOCK_SOURCE_ALT_0 0
#define KINETIS_ADC16_CLOCK_SOURCE_ALT_1 1
#define KINETIS_ADC16_CLOCK_SOURCE_ALT_2 2
#define KINETIS_ADC16_CLOCK_SOURCE_ALT_3 3
#define KINETIS_ADC16_CLOCK_SOURCE_ASYNC KINETIS_ADC16_CLOCK_SOURCE_ALT_3

#define KINETIS_ADC16_CLOCK_DIVIDER_1 0
#define KINETIS_ADC16_CLOCK_DIVIDER_2 1
#define KINETIS_ADC16_CLOCK_DIVIDER_4 2
#define KINETIS_ADC16_CLOCK_DIVIDER_8 3

#define KINETIS_ADC16_LONG_SAMPLE_CYCLE_24 0
#define KINETIS_ADC16_LONG_SAMPLE_CYCLE_16 1
#define KINETIS_ADC16_LONG_SAMPLE_CYCLE_10 2
#define KINETIS_ADC16_LONG_SAMPLE_CYCLE_6  3
#define KINETIS_ADC16_LONG_SAMPLE_DISABLED 4

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_ADC_KINETIS_ADC_H_