manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: blixttech
      url-base: https://github.com/blixttech

  #
  # Please add items below in alphabetic order
  # Only add a remote if different from the default
  projects:
    - name: cmsis
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: zephyr-os/modules/hal/cmsis  
    - name: mcuboot                                                              
      revision: e88113bbebe34ff2ccc6627ffae885cfeed6fdfd                         
      path: zephyr-os/bootloader/mcuboot
    - name: mcumgr
      revision: 5885efb7cabf7b566577b73129c9d277d7d8848d
      path: zephyr-os/modules/lib/mcumgr
    - name: hal_nxp
      remote: blixttech
      revision: 274f6a6e68f81de8730253407448444caa4ef542
      path: zephyr-os/modules/hal/nxp
    - name: tinycbor                                                             
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
      path: zephyr-os/modules/lib/tinycbor                                                 
    - name: zephyr
      revision: b8c78e254ff875680e99c9f131fbe285c4575927
      path: zephyr-os/zephyr
      west-commands: scripts/west-commands.yml


  self:
    path: .
