#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_

#define KINETIS_FTM_PRESCALE_DIVIDE_1	0
#define KINETIS_FTM_PRESCALE_DIVIDE_2	1
#define KINETIS_FTM_PRESCALE_DIVIDE_4	2
#define KINETIS_FTM_PRESCALE_DIVIDE_8	3
#define KINETIS_FTM_PRESCALE_DIVIDE_16	4
#define KINETIS_FTM_PRESCALE_DIVIDE_32	5
#define KINETIS_FTM_PRESCALE_DIVIDE_64	6
#define KINETIS_FTM_PRESCALE_DIVIDE_128 7

#define KINETIS_FTM_SYSTEM_CLK	 1U
#define KINETIS_FTM_FIXED_CLK	 2U
#define KINETIS_FTM_EXTERNAL_CLK 3U

#define KINETIS_FTM_CHNL_0 0
#define KINETIS_FTM_CHNL_1 1
#define KINETIS_FTM_CHNL_2 2
#define KINETIS_FTM_CHNL_3 3
#define KINETIS_FTM_CHNL_4 4
#define KINETIS_FTM_CHNL_5 5
#define KINETIS_FTM_CHNL_6 6
#define KINETIS_FTM_CHNL_7 7

#define KINETIS_FTM_CHNL_0_TRIGGER	(1U << 4)
#define KINETIS_FTM_CHNL_1_TRIGGER	(1U << 5)
#define KINETIS_FTM_CHNL_2_TRIGGER	(1U << 0)
#define KINETIS_FTM_CHNL_3_TRIGGER	(1U << 1)
#define KINETIS_FTM_CHNL_4_TRIGGER	(1U << 2)
#define KINETIS_FTM_CHNL_5_TRIGGER	(1U << 3)
#define KINETIS_FTM_CHNL_6_TRIGGER	(1U << 8)
#define KINETIS_FTM_CHNL_7_TRIGGER	(1U << 9)
#define KINETIS_FTM_INIT_TRIGGER	(1U << 6)
#define KINETIS_FTM_RELOAD_INIT_TRIGGER (1U << 7)

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_