#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_CMP_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_CMP_H_

#define KINETIS_CMP_HYSTERESIS_L0       0U
#define KINETIS_CMP_HYSTERESIS_L1       1U
#define KINETIS_CMP_HYSTERESIS_L2       2U
#define KINETIS_CMP_HYSTERESIS_L3       3U

#define KINETIS_CMP_EDGE_RISING         0x10U
#define KINETIS_CMP_EDGE_FALLING        0x8U

#endif /* _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_CMP_H_ */