manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: blixttech
      url-base: https://github.com/blixttech

  # Please add items below in alphabetic order
  # Only add a remote if different from the default
  projects:
    - name: cmsis
      revision: 093de61c2a7d12dc9253daf8692f61f793a9254a
      path: modules/hal/cmsis
    - name: hal_nxp
      revision: 708c95825b0d5279620935a1356299fff5dfbc6e
      path: modules/hal/nxp
    - name: mbedtls
      revision: 7fed49c9b9f983ad6416986661ef637459723bcb
      path: modules/crypto/mbedtls
    - name: mcuboot
      revision: 13f63976bca672ee018f9d55f1e31f02f4135b64
      path: modules/bootloader/mcuboot
    - name: zcbor
      revision: a0d6981f14d4001d6f0d608d1a427f9bc6bb6d02
      path: modules/lib/zcbor
    - name: zephyr
      revision: 4256cd41df6c60f1832fd2deb14edc30ac7debab
      path: zephyr
      west-commands: scripts/west-commands.yml
      import: false
    - name: zero-coap-payload
      remote: blixttech
      revision: 039583add86d0da04bdc0123d4224e0bcd5fd967
      path: modules/zero/coap-payload

  self:
    path: manifest
