manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: blixttech
      url-base: https://github.com/blixttech

  # Please add items below in alphabetic order
  # Only add a remote if different from the default
  projects:
    - name: cmsis
      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3
      path: modules/hal/cmsis
    - name: hal_nxp
      revision: d957472002a3758154f402e982d95ce90cf58e12
      path: modules/hal/nxp
    - name: mbedtls
      revision: 6e166050075688fd3cf3d0cb3fc34a1c52df2496
      path: modules/crypto/mbedtls
    - name: mcuboot
      revision: 750678e33819b95756203e5db1ba827baee35708
      path: modules/bootloader/mcuboot
    - name: zcbor
      revision: 0.6.0
      path: modules/lib/zcbor
    - name: zephyr
      revision: zephyr-v3.3.0
      path: zephyr
      west-commands: scripts/west-commands.yml
      import: false
    - name: zero-control-messages
      remote: blixttech
      revision: 7e2fda793f12eeda6d792e5acae5aa05e6671589
      path: modules/zero/zc-messages

  self:
    path: manifest
