#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_

#define IC_EDGE_NONE                        0
#define IC_EDGE_SINGLE_RISING               1
#define IC_EDGE_SINGLE_FALLING              2
#define IC_EDGE_SINGLE_RISING_FALLING       3
#define IC_EDGE_DUAL_PULSE_RISING           4
#define IC_EDGE_DUAL_PULSE_FALLING          5
#define IC_EDGE_DUAL_PERIOD_RISING          6
#define IC_EDGE_DUAL_PERIOD_FALLING         7

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_