#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_

#define INPUT_CAPTURE_EDGE_RISING       0
#define INPUT_CAPTURE_EDGE_FALLING      1
#define INPUT_CAPTURE_EDGE_BOTH         2

#define INPUT_CAPTURE_MODE_SINGLE       0
#define INPUT_CAPTURE_MODE_CONTINOUES   1

#endif // ZEPHYR_INCLUDE_DT_BINDINGS_TIMER_INPUT_CAPTURE_H_