#ifndef _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_
#define _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_

#define KINETIS_FTM_CLK_SRC_SYSTEM_CLK          1U
#define KINETIS_FTM_CLK_SRC_FIXED_CLK           2U
#define KINETIS_FTM_CLK_SRC_EXTERNAL_CLK        3U

#endif // _ZEPHYR_INCLUDE_DT_BINDINGS_KINETIS_FTM_H_